#! /usr/bin/env python
from IPython import embed

sorted_links = {}

with open('links-simple-sorted.txt') as fh:
    sorted_links_data = fh.readlines()

with open('titles-sorted.txt') as fh:
    titles_data = fh.readlines()

for link in sorted_links_data:
    fudge = -1
    link = link.split(':')
    link_name = titles_data[int(link[0]) + fudge]
    links = link[1].strip().split()
    sorted_links[link_name] = [
        titles_data[int(link) + fudge]
        for link in links
    ]

def findlinks(target_link):
    return sorted_links[target_link]

if __name__ == '__main__':
    embed()
